swagger: '2.0'
info:
  version: '1.0'
  title: "HUBusivi"
  description: REST Api per gestire gli esami
  license:
    name: MIT
    url: https://github.com/apiaryio/polls-api/blob/master/LICENSE
host: ingegneriasoftwa2.herokuapp.com
basePath: /
schemes:
- https
consumes:
- application/json
produces:
- application/json 
paths:
  
  /students:
    post:
      tags: 
      - "Users"
      summary: Add a student on the database
      operationId: addStudent
      parameters:
        - name: student_attributes
          in: query
          description: data of the student
          type: string
          x-example: "Pinco pallino"
      responses:
        400:
          description: Bad request
        404:
          description: Resources not found
        200:
          description: Marks average
  
    delete:
      summary: Remove a student from the database
      operationId: addStudent
      parameters:
        - name: matricola
          in: query
          description: corso di cui fare la media delle valutazioni
          type: string
          x-example: "Pinco pallino"
      responses:
        400:
          description: Bad request
        404:
          description: Resources not found
        200:
          description: Marks average
  
  /assignment:
    post: 
        tags: 
        - "Assignment"
        
        summary: Add an Assignment(only teacher)
        operationId: AddAssignment
        parameters:
          - name: Name 
            in: query
            description: Name of assignment
            type: string
            x-example: "Compito Gennaio"
          - name: Date
            in: query
            description: Date of assignment
            type: string
            x-exaple: "11/11/2018"
          - name: Delivery date
            in: query
            description: Delivery date of assignment
            type: string
            x-exaple: "12/12/2018"
          
        responses:
          400:
            description: Bad request
          404:
            description: Resources not found
          200:
            description: Successful response
  
    delete:
      summary: Remove an assignment
      operationId: removeAssignment
      parameters:
        - name: Name
          in: query
          description: name of assignment
          type: string
          x-example: "Compito Gennaio"
        - name: Date
          in: query
          description: Date of assignment
          type: string
          x-exaple: "11/11/2018"
        - name: Delivery date
          in: query
          description: Delivery date of assignment
          type: string
          x-exaple: "12/12/2018"
      responses:
        400:
          description: Bad request
        404:
          description: Resources not found
        200:
          description: Successful response  
  
    put:
      summary: Update an assignment
      operationId: updateAssignment
      parameters:
        - name: Name
          in: query
          description: name of assignment
          type: string
          x-example: "Compito Gennaio"
      responses:
        400:
          description: Bad request
        404:
          description: Resources not found
        200:
          description: Successful response
          
  /marks:
    
    post:
      tags:
      - "Marks"
      summary: Add a Mark
      operationId: addMark
      parameters:
        - name: mark
          in: query
          description: voto da aggiungere
          type: integer
          x-example: 22
        - name: matricola
          in: query
          description: matricola of the student 
          type: integer
          x-example: 123456
        - name: course_id
          in: query
          description: course id of the mark
          type: integer
          x-example: 113355
      responses:
        400:
          description: Bad request
        404:
          description: Resources not found
        200:
          description: Successful response
    
    delete:
      summary: Remove a Mark of a specific exam of a student
      operationId: removeMark
      parameters:
        - name: matricola
          in: query
          description: matricola of the student
          type: integer
          x-example: 123456
        - name: course_id
          in: query
          description: course id of the mark
          type: integer
          x-example: 113355
      responses:
        400:
          description: Bad request
        404:
          description: Resources not found
        200:
          description: Successful response

    put:
      summary: Update a Mark of a specific exam of a student
      operationId: updateMark
      parameters:
        - name: mark
          in: query
          description: mark to update
          type: integer
          x-example: 22
        - name: matricola
          in: query
          description: matricola of the student
          type: integer
          x-example: 123456
        - name: course_id
          in: query
          description: course id of the mark
          type: integer
          x-example: 113355
      responses:
        400:
          description: Bad request
        404:
          description: Resources not found
        200:
          description: Successful response
          
  /marks/avg:
    post:
      description: >-
        Calculate the marks average about a specific exam of a course.
      summary: Average course marks
      operationId: addMark
      parameters:
        - name: course_id
          in: query
          description: exam id to be averaged
          type: integer
          x-example: 113355
      responses:
        400:
          description: Bad request
        404:
          description: Resources not found
        200:
          description: Marks average
          
  
  /courses:
    put:
      summary: Add a course(teacher)/Join a course(student)
      operationId: addCourse
      parameters:
        - name: course data
          in: query
          description: course data
          type: string
          x-example: 'Ingegneria del software 2'
      responses:
        400:
          description: Bad request
        404:
          description: Resources not found
        200:
          description: Successful response
  
    get:
      tags:
      - "Courses"
      summary: Get the list of all your courses
      operationId: coursesList
      parameters:
        - name: matricola
          in: query
          description: matricola of the user
          type: integer
          x-example: 123456
      responses:
        400:
          description: Bad request
        404:
          description: Resources not found
        200:
          description: List of all your courses
  
    delete:
      summary: Remove a course(teacher only)/Leave a course(student only)
      operationId: removeCourse
      parameters:
        - name: course_id
          in: query
          description: course id of the mark
          type: integer
          x-example: 113355
      responses:
        400:
          description: Bad request
        404:
          description: Resources not found
        200:
          description: Successful response
  
    post:
      summary: Update a Course(teacher only)
      operationId: updateMark
      parameters:
        - name: course info
          in: query
          description: course info
          type: string
          x-example: 'Ingegneria del software - 2'
        - name: course_id
          in: query
          description: course id
          type: integer
          x-example: 113355
      responses:
        400:
          description: Bad request
        404:
          description: Resources not found
        200:
          description: Successful response