swagger: '2.0'
info:
  version: '1.0'
  title: "HUBusivi"
  description: Progetto Ingegneria Del Software 2 - Università degli studi di Trento
  license:
    name: MIT
    url: https://github.com/apiaryio/polls-api/blob/master/LICENSE
host: ingegneriasoftwa2.herokuapp.com
basePath: /
schemes:
- https
consumes:
- application/json
produces:
- application/json
paths:
  /assignment:
    x-summary: Assignment
    post: 
        description: >-
         Teacher creates a new assignment
        summary: Add an Assignment
        operationId: AddAssignment
        parameters:
          - name: Name 
            in: query
            description: Name of assignment
            type: string
            x-example: "Compito Gennaio"
          - name: Date
            in: query
            description: Date of assignment
            type: string
            x-exaple: "11/11/2018"
          - name: Delivery date
            in: query
            description: Delivery date of assignment
            type: string
            x-exaple: "12/12/2018"
          
        responses:
          400:
            description: Bad request
          404:
            description: Resources not found
          200:
            description: Successful response
  /assignment/remove:
    x-summary: Remove assignment
    delete:
      description: >-
        Remove a specific assignment
      summary: Remove an assignment
      operationId: removeAssignment
      parameters:
        - name: Name
          in: query
          description: name of assignment
          type: string
          x-example: "Compito Gennaio"
        - name: Date
          in: query
          description: Date of assignment
          type: string
          x-exaple: "11/11/2018"
        - name: Delivery date
          in: query
          description: Delivery date of assignment
          type: string
          x-exaple: "12/12/2018"
      responses:
        400:
          description: Bad request
        404:
          description: Resources not found
        200:
          description: Successful response  
  /assignment/update:
    x-summary: Update assignment
    delete:
      description: >-
        Update a specific assignment
      summary: Update an assignment
      operationId: updateAssignment
      parameters:
        - name: Name
          in: query
          description: name of assignment
          type: string
          x-example: "Compito Gennaio"
      responses:
        400:
          description: Bad request
        404:
          description: Resources not found
        200:
          description: Successful response  
  /marks:
    x-summary: Marks
    post:
      description: >-
        Add a mark for a specific test for a student.
      summary: Add a Mark
      operationId: addMark
      parameters:
        - name: mark
          in: query
          description: voto da aggiungere
          type: integer
          x-example: 22
        - name: matricola
          in: query
          description: matricola of the student 
          type: integer
          x-example: 123456
        - name: course_id
          in: query
          description: course id of the mark
          type: integer
          x-example: 113355
      responses:
        400:
          description: Bad request
        404:
          description: Resources not found
        200:
          description: Successful response
  /marks/remove:
    x-summary: Remove marks
    delete:
      description: >-
        Remove a mark of a specific exam of a student.
      summary: Remove a Mark
      operationId: removeMark
      parameters:
        - name: matricola
          in: query
          description: matricola of the student
          type: integer
          x-example: 123456
        - name: course_id
          in: query
          description: course id of the mark
          type: integer
          x-example: 113355
      responses:
        400:
          description: Bad request
        404:
          description: Resources not found
        200:
          description: Successful response
  /marks/update:
    x-summary: Update marks
    put:
      description: >-
        Update a mark of an specific exam of a student.
      summary: Update a Mark
      operationId: updateMark
      parameters:
        - name: mark
          in: query
          description: mark to update
          type: integer
          x-example: 22
        - name: matricola
          in: query
          description: matricola of the student
          type: integer
          x-example: 123456
        - name: course_id
          in: query
          description: course id of the mark
          type: integer
          x-example: 113355
      responses:
        400:
          description: Bad request
        404:
          description: Resources not found
        200:
          description: Successful response
          
  /marks/avg:
    x-summary: Average course marks
    post:
      description: >-
        Calculate the marks average about a specific exam of a course.
      summary: Average course marks
      operationId: addMark
      parameters:
        - name: course_id
          in: query
          description: exam id to be averaged
          type: integer
          x-example: 113355
      responses:
        400:
          description: Bad request
        404:
          description: Resources not found
        200:
          description: Marks average
          
  /students/add:
    x-summary: Add a student on the database
    post:
      description: >-
         Add a student on the database.
      summary: Add a student on the database
      operationId: addStudent
      parameters:
        - name: student_attributes
          in: query
          description: data of the student
          type: string
          x-example: "Pinco pallino"
      responses:
        400:
          description: Bad request
        404:
          description: Resources not found
        200:
          description: Marks average
  /students/remove:
    x-summary: Remove a student from the database
    delete:
      description: >-
        Remove a student from the database.
      summary: Remove a student from the database
      operationId: addStudent
      parameters:
        - name: matricola
          in: query
          description: corso di cui fare la media delle valutazioni
          type: string
          x-example: "Pinco pallino"
      responses:
        400:
          description: Bad request
        404:
          description: Resources not found
        200:
          description: Marks average
  /courses:
    x-summary: List of courses
    post:
      description: >-
        Get the list of all your courses.
      summary: List of courses
      operationId: coursesList
      parameters:
        - name: matricola
          in: query
          description: matricola of the user
          type: integer
          x-example: 123456
      responses:
        400:
          description: Bad request
        404:
          description: Resources not found
        200:
          description: List of all your courses
  /courses/add:
    x-summary: Add course
    delete:
      description: >-
        Add a course(teacher)/Join a course(student)
      summary: Add a course
      operationId: addCourse
      parameters:
        - name: course data
          in: query
          description: course data
          type: string
          x-example: 'Ingegneria del software 2'
      responses:
        400:
          description: Bad request
        404:
          description: Resources not found
        200:
          description: Successful response
  /courses/remove:
    x-summary: Remove courses
    delete:
      description: >-
        Remove a course(teacher only)/Leave a course(student only)
      summary: Remove a course
      operationId: removeCourse
      parameters:
        - name: course_id
          in: query
          description: course id of the mark
          type: integer
          x-example: 113355
      responses:
        400:
          description: Bad request
        404:
          description: Resources not found
        200:
          description: Successful response
  /courses/update:
    x-summary: Update courses
    put:
      description: >-
        Update a course(teacher only)
      summary: Update a Mark
      operationId: updateMark
      parameters:
        - name: course info
          in: query
          description: course info
          type: string
          x-example: 'Ingegneria del software - 2'
        - name: course_id
          in: query
          description: course id
          type: integer
          x-example: 113355
      responses:
        400:
          description: Bad request
        404:
          description: Resources not found
        200:
          description: Successful response