swagger: '2.0'
info:
  version: '1.0'
  title: "HUBusivi"
  description: Progetto Ingegneria Del Software 2 - Università degli studi di Trento
  license:
    name: MIT
    url: https://github.com/apiaryio/polls-api/blob/master/LICENSE
host: ingegneriasoftwa2.herokuapp.com
basePath: /
schemes:
- https
consumes:
- application/json
produces:
- application/json
paths:
  /marks:
    x-summary: Marks
    post:
      description: >-
        Aggiugere un voto corrispondente ad un esame di un determinato studente.
      summary: Add a Mark
      operationId: addMark
      parameters:
        - name: mark
          in: query
          description: voto da aggiungere
          type: integer
          x-example: 22
        - name: matricola
          in: query
          description: matricola studente a cui aggiungere il voto
          type: integer
          x-example: 123456
        - name: course_id
          in: query
          description: corso corrispondente al voto
          type: integer
          x-example: 113355
      responses:
        default:
          description: Bad request
        200:
          description: Successful response
          schema:
            $ref: ''
definitions:
  mark:
    title: Mark
    type: integer
    properties:
      mark:
        type: integer
      published_at:
        type: string
    required:
      - course_id
      - student_id
  course_id:
    title: course_id
    type: integer
    properties:
      id:
        type: integer
  student_id:
    title: student_id
    type: integer
    properties:
      id:
        type: integer